# Generated by Django 5.2.15 on 2026-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('media_type', models.CharField(max_length=20)),
                ('is_deepfake', models.BooleanField()),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
